### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lavhe** [JMRSquared/JMRSquared#6]
- [x] Redesign the Database to have a Collection of businesses and read accordingly
- [x] User profile page add more functionality
- [x] Change login details
- [x] Taxify must have its own admin and client
- [x] More security on Taxify , like login for driver.
- [x] Add more businesses functionality
- [x] Added Push notifications , reminders and alerts
- [x] Tenant portal (Get rent reminders / Alerts / manage account / lease agreement staff)
- [x] Handle 512 errors and use AUTH for all axios 
- [x] on AddBusiness.vue , after saving the business disable all the buttons , and redirect to home
- [x] Add the businesses one by one (SetTimeout)
- [ ] Add calender view for transactions
